/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ContactInfo = IDL.Record({
  'socialLinks' : IDL.Vec(IDL.Text),
  'email' : IDL.Text,
  'phone' : IDL.Text,
});
export const SenderType = IDL.Variant({ 'bot' : IDL.Null, 'user' : IDL.Null });
export const ChatMessage = IDL.Record({
  'sender' : SenderType,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
});

export const idlService = IDL.Service({
  'getContactInfo' : IDL.Func([], [IDL.Opt(ContactInfo)], ['query']),
  'getConversation' : IDL.Func([], [IDL.Vec(ChatMessage)], ['query']),
  'sendMessage' : IDL.Func([IDL.Text], [IDL.Text], []),
  'updateContactInfo' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ContactInfo = IDL.Record({
    'socialLinks' : IDL.Vec(IDL.Text),
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  const SenderType = IDL.Variant({ 'bot' : IDL.Null, 'user' : IDL.Null });
  const ChatMessage = IDL.Record({
    'sender' : SenderType,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  
  return IDL.Service({
    'getContactInfo' : IDL.Func([], [IDL.Opt(ContactInfo)], ['query']),
    'getConversation' : IDL.Func([], [IDL.Vec(ChatMessage)], ['query']),
    'sendMessage' : IDL.Func([IDL.Text], [IDL.Text], []),
    'updateContactInfo' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };